version: "3.9"

services:
    data-base:
        image: postgres:13
        ports:
            -  "5432:5432"
        environment:
            - POSTGRES_DB=test
            - POSTGRES_USER=root
            - POSTGRES_PASSWORD=root
